[package]
name = "lr_parser"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch-rs="*"
prettytable="*"
once_cell="*"